# Generated by Django 4.2.6 on 2023-10-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='definition',
            field=models.CharField(default=' ', max_length=300),
            preserve_default=False,
        ),
    ]
