# Generated by Django 4.2.6 on 2023-10-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='definition',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
